[package]
name = "arcane-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
deno_core = "=0.385.0"
deno_ast = { version = "=0.53.0", features = ["transpiling"] }
deno_error = "=0.7.3"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
